CREATE TABLE IF NOT EXISTS EmployeeCar (
  ID SERIAL PRIMARY KEY NOT NULL,
  EmployeeID INT REFERENCES Employee(ID) NOT NULL,
  CarID INT REFERENCES Car(ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS Timeframe (
  ID SERIAL PRIMARY KEY NOT NULL,
  Day TEXT NOT NULL,
  TimeFrom time with time zone NOT NULL,
  TimeTo time with time zone NOT NULL,
  CarID INT REFERENCES Car(ID) NOT NULL,
  EmployeeCarID INT REFERENCES EmployeeCar(ID) NOT NULL
);